# 配置端口
server:
  port: 8088

#数据源配置
spring:
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库 url
    url: jdbc:mysql://127.0.0.1:3306/arch?characterEncoding=UTF-8&serverTimezone=UTC
    #用户名
    username: root
    #密码
    password: root
  cache:
    type: redis
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=30s
  redis:
    database: 0 
    host: 127.0.0.1 
    password: 
    port: 6379 
    ssl: false 
    timeout: 5000 
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 0
    
logging:
  config: classpath:logback.xml
  level:
    com.archevolution: info
  path: /logs